name: Build and Deploy Python Azure Function

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Match your Function App runtime

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

    - name: Archive Function App
      run: |
        zip -r functionapp.zip host.json AskFunction

    - name: Deploy to Azure Function App
      uses: azure/functions-action@v1
      with:
        app-name: 'jeliv-poc-fapp-dev-sn-01'  # Your Function App name
        package: 'functionapp.zip'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
